bookAbvs=['DMG',
          'MIC',
          'CAdv',
          'CCha',
          'CMage',
          'CSco',
          'CWar',
          'DMG2',
          'DMag',
          'Drac',
          'RotD',
          'RoS',
          'RotW',
          'DotU',
          'Und',
          'Dung',
          'Frost',
          'Sand',
          'Storm',
          'ToB']

bookNames=['Dungeon Master\'s Guide',
           'Magic Item Compendium',
           'Complete Adventurer',
           'Complete Champion',
           'Complete Mage',
           'Complete Scoundrel',
           'Complete Warrior',
           'Dungeon Master\'s Guide II',
           'Dragon Magic',
           'Draconomicon',
           'Races of the Dragon',
           'Races of Stone',
           'Races of the Wild',
           'Drow of the Underdark',
           'Underdark',
           'Dungeonscape',
           'Frostburn',
           'Sandstorm',
           'Stormwrack',
           'Tome of Battle']
